config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "home#index"

  post "follower_requests/:user_id" => "follower_requests#create", as: :follower_create_specific

  resources :follower_requests

  resources :posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/follow_request.rb
class FollowRequest < ApplicationRecord
  belongs_to :sender, class_name: "User", foreign_key: "sender_id"
  belongs_to :receiver, class_name: "User", foreign_key: "receiver_id"

  validates :sender_id, uniqueness: { scope: :receiver_id }
  validate :cannot_follow_self

  def cannot_follow_self
    if sender_id == receiver_id
      errors.add(:sender_id, "can't follow self")
    end
  end

  def accept
    Follower.create(user_id: receiver_id, follower_id: sender_id)
  end
end

app/models/follower.rb
class Follower < ApplicationRecord
  validates :user_id, :follower_id, presence: true

  belongs_to :user, class_name: "User", foreign_key: "user_id"
  belongs_to :follower, class_name: "User", foreign_key: "follower_id"
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: "User", foreign_key: "author_id"

  validates :content, :author_id, presence: true

  has_many :replies, class_name: "Post", foreign_key: "parent_id"
  belongs_to :parent, class_name: "Post", optional: true, foreign_key: "parent_id"
end

app/models/user.rb
class User < ApplicationRecord
  has_many :follow_requests_sent, class_name: "FollowRequest", foreign_key: "sender_id"
  has_many :follow_requests_received, class_name: "FollowRequest", foreign_key: "receiver_id"

  has_and_belongs_to_many :followers, class_name: "User", join_table: "followers", foreign_key: "user_id", association_foreign_key: "follower_id"
  has_and_belongs_to_many :following, class_name: "User", join_table: "followers", foreign_key: "follower_id", association_foreign_key: "user_id"

  has_many :posts, class_name: "Post", foreign_key: "author_id"

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/follower_requests_controller.rb
class FollowerRequestsController < ApplicationController
  before_action :authenticate_user!

  new do
    raise "Not implemented"
  end

  def create
    puts "params: #{params}"
    puts "#{current_user.id} != #{params[:user_id]}"
    if current_user.id != params[:user_id].to_i
      raise "Not authorized"
    end

    FollowRequest.create(sender_id: current_user.id, receiver_id: params[:follow_id])
    redirect_to follower_requests_path
  end

  def destroy
    req = FollowRequest.find(params[:id])
    if req.sender_id == current_user.id || req.receiver_id == current_user.id
      req.destroy
      redirect_to follower_requests_path
    else
      raise "Not authorized"
    end
  end

  def update
    req = FollowRequest.find(params[:id])
    if req.receiver_id == current_user.id
      req.accept
      req.destroy
      redirect_to follower_requests_path
    else
      raise "Not authorized"
    end
  end

  def index
    @requests_sent = FollowRequest.where(sender_id: current_user.id)
    @requests_received = FollowRequest.where(receiver_id: current_user.id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  def index
    @posts = Post.all.select { |u| u.parent_id == nil }
                     .sort_by { |x| x[:created_at] }.reverse
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!

  def show
    @post_id = params[:id].to_i
    @post = Post.find(@post_id)
  end

  def new
    @post = Post.new
    if params[:reply_to] != nil
      @parentPost = Post.find(params[:reply_to])
      @post.parent_id = params[:reply_to]
    end
  end

  def create
    @post = Post.new(post_params)
    @post.author_id = current_user.id
    if @post.save
      redirect_to root_path
    else
      render :new
    end
  end

  def post_params
    params.require(:post).permit(:content, :media, :parent_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/follower_requests_helper.rb
module FollowerRequestsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/follower_requests/index.html.erb
<div class="col">
    <H2>Requests Sent</H2>
    <% @requests_sent.each do |r| %>
        <div>
            <%= r.receiver.email %>
        </div>
    <% end %>
    <H2>Requests Received</H2>
    <% @requests_received.each do |r| %>
        <div>
            <%= r.sender.email %>
            <%= link_to "Accept", follower_request_path(r.id), method: :put %>
            <%= link_to "Reject", follower_request_path(r.id), method: :delete %>
        </div>
    <% end %>
</div>

app/views/home/index.html.erb
<div>
    <h3>Posts</h3>
    <%= link_to "New Post", controller: "posts", action: "new" %>
    <ul class="list-group">
        <% @posts.each do |p| %>
            <li class="list-group"> 
                <%= render partial: "posts/post", locals: { post: p, expand_replies: false } %>
            </li>
        <% end %>
    </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Ruby Rails Postgres" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice text-center"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div class="container">
      <div class="row ">
        <h1 class="col-lg-2 text-left">
          <%= link_to("🏠", root_path) %>
        </h1> 
        <div class="col-lg-8 text-center">
          <h1>💃🕺 Welcome to The Party 🕺💃</h1>   
        </div>
        <div class="col-lg-2 text-left">
          <% if current_user # Logged in User Content %>
            <p><%= current_user.email %></br>
            <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
            </p>
          <% end %>
        </div>
      </div>

<% if current_user # Logged in User Content %>
      <%
        @user = User.find(current_user.id)
        @users = User.all.map { |u| { id: u.id, email: u.email, is_following: u.followers.any? { |f| f.id == @user.id  } } }
      %>
  <hr/>
      <div class="row align-items-start">
        <div class="col-lg-2">
            <h3>look who's here!</h3>
            <ul class="list-group">
                <% @users.each do |user| %>
                    <% if (user[:id] != current_user.id)  %>
                        <li class="list-group-item"><%= user[:email] %>  
                            <%=if user[:is_following]
                                    button_to 'unfollow', follower_request_path(current_user.id), params: {follow_id: user[:id]}, method: :delete 
                            else 
                                    button_to 'follow', follower_request_path(current_user.id), params: {follow_id: user[:id]}, method: :post
                            end %>
                        </li>
                    <% end %>
                <% end %>
            </ul>
        </div>

        <div class="col-lg-8 text-left">
          <%= yield %>
        </div>

        <div class="col-lg-2 text-left">
            <div>
              <h2>Following</h2>
              <div>
                    <% if @user.following.any?  %>
                        <ol>
                            <% @user.following.each do |u|  %>
                            <li><%=u.email%></li>
                            <% end %>
                        </ol>
                    <% else %>
                        <p>n/a</p>
                    <% end %>
              </div>
          </div>

          <div>
                <h2>Followers</h2>
                <div>
                    <% if @user.followers.any?  %>
                        <ol>
                            <% @user.followers.each do |u|  %>
                            <li><%=u.email%></li>
                            <% end %>
                        </ol>
                    <% else %>
                        <p>n/a</p>
                    <% end %>
                </div>
          </div>

            <% # TODO: This should be a partial %>
          <div>
                <h3><%= link_to("Requests", follower_requests_path) %></h3>  
                <h4>Sent</h4>
                    <% if @user.follow_requests_sent.any? %>
                        <ul>
                            <% @user.follow_requests_sent.each do |u|  %>
                            <li><%=u.receiver.email%></li>
                            <% end %>
                        </ul>
                    <% else %>
                        <p>n/a</p>
                    <% end %>
                <h4>Received</h4>
                    <% if @user.follow_requests_received.any? %>
                        <ul>
                            <% @user.follow_requests_received.each do |u|  %>
                            <li><%=u.sender.email%></li>
                            <% end %>
                        </ul>
                    <% else %>
                        <p>n/a</p>
                    <% end %>
          </div>
        </div>  
      <% else # Logged out user content %>
      <div class="col-lg-12 text-center">
        <%= yield %>
        </div>
      <%  end %>
      </div> 
    </div>
  </body>
</html>

app/views/posts/_post.html.erb
<div>
    <h6>from <%= post.author.email %> at <%= post.created_at%></h6>
    <% @replies = post.replies.to_a %>
    <p><%= link_to "#{post.content} (#{@replies.count} replies)", { controller: "posts", action: "show", id: post.id}, style: 'text-decoration:none' %>
    <span style="margin-left:40px" class="no-underline">
        <br/><%= link_to "💬", { controller: "posts", action: "new", params: { :reply_to => post.id } } , style: 'text-decoration:none' %>
    </span>
    </p>

    <% 
    if !post.media.blank?
        concat "<div>#{image_tag post.media}</div>"
    end 
    %>

    <% if expand_replies%>
    <hr/>

    <div style="margin-left:40px">
        <ul class="list-group">
            <% @replies.each do |r| %>
                <li class="list-group"><div>
                <%= render partial: "posts/post", locals: {post:r, expand_replies:true} %>
                </li>
            <% end %>
        </ul>
    </div>  
    <% end %>
</div>

app/views/posts/create.html.erb
<h1>CREATE POST</h1>

app/views/posts/new.html.erb
<% if @parentPost != nil %>
          <h1>REPLY TO</h1>
          <%= render partial: "posts/post", locals: {post:@parentPost, expand_replies:false} %>
        <% else %>
         <h1>NEW POST</h1>
   %<% end %>

<%= form_with(model: @post, local: true) do |form| %>
  <div class="field">
	<%= form.label :content %>
	<%= form.text_area :content %>
  </div>

  <div class="field">
	<%= form.label :media %>
	<%= form.text_field :media %>
  </div>

    
    <%= if @post.parent_id != nil
            form.hidden_field :parent_id, value:  @post.parent_id
        end
     %>

  <div class="actions">
	<%= form.submit "Save" %>
  </div>
<% end %>

app/views/posts/show.html.erb
<%= render partial: "post", locals: {post:@post, expand_replies: true} %>